export const FETCH_POSTS_SUCCESS: string = "FETCH_POSTS_SUCCESS";
export const ADD_TO_CART: string = "ADD_TOCART";
export const ADD_TO_FAVOURITE: string = "ADD_TO_FAVOURITE";
export const FETCH_BESTSELLERS: string = "FETCH_BESTSELLERS";
export const FETCH_NEW_ARRIVALS: string = "FETCH_NEW_ARRIVALS";
export const REMOVE_ITEM_FROM_CART: string = "REMOVE_ITEM_FROM_CART";
export const REMOVE_ITEM_FROM_FAVOURITE: string = "REMOVE_ITEM_FROM_FAVOURITE";