
export const FETCH_USER_SUCCESS: string = 'FETCH_USER_SUCCESS';
export const FETCH_POSTS_SUCCESS: string = 'FETCH_POSTS_SUCCESS';
export const DELETE_POST_SUCCESS: string = 'DELETE_POST_SUCCESS';
export const ADD_POST_SUCCESS: string = 'ADD_POST_SUCCESS';
export const ADD_COMMENT_SUCCESS: string = 'ADD_COMMENT_SUCCESS';
export const FETCH_COMMENTS_SUCCESS: string = "FETCH_COMMENTS_SUCCESS";
export const FETCH_SINGLE_POST_SUCCESS: string = "FETCH_SINGLE_POST_SUCCESS"
export const FETCH_USER_NAME_SUCCESS: string = 'FETCH_USER_NAME_SUCCESS';